### ISSUE TITLE
Paypal button is throwing error

### ISSUE THREAD

**Issue by kbuzby** [kbuzby/studiobalu#21]

**Comment by kbuzby** [comment]
This was a bug with paypal's sandbox environment.

**Comment by pradipyadavpk** [comment]
I am stuck last 5 days and no luck...
somebody help... It was really-really worst decision to add paypal in my web app.
{stack: "Error: No value passed to payment↵ at https://w…aypalobjects.com/api/checkout.4.0.166.js:2856:13)", errtype: "[object Error]", timestamp: 1512406360681, windowID: "99a6bf0489", pageID: "d6d9926518", …}country: "GB"env: "sandbox"errtype: "[object Error]"host: "www.sandbox.paypal.com"lang: "en"pageID: "d6d9926518"path: "/webapps/hermes/button"prev_corr_ids: ""referer: "http://localhost:4567"stack: "Error: No value passed to payment↵ at https://www.paypalobjects.com/api/checkout.4.0.166.min.js:14:187628↵ at https://www.paypalobjects.com/api/checkout.4.0.166.min.js:14:168195↵ at e.dispatch (https://www.paypalobjects.com/api/checkout.4.0.166.min.js:14:168649)↵ at e.resolve (https://www.paypalobjects.com/api/checkout.4.0.166.min.js:14:167373)↵ at https://www.paypalobjects.com/api/checkout.4.0.166.min.js:14:167026↵ at ↵ at Object._RECEIVE_MESSAGE_TYPE.(anonymous function) [as postrobot_message_response] (https://www.paypalobjects.com/api/checkout.4.0.166.js:2936:122)↵ at receiveMessage (https://www.paypalobjects.com/api/checkout.4.0.166.js:2835:77)↵ at messageListener (https://www.paypalobjects.com/api/checkout.4.0.166.js:2856:13)"timestamp: 1512406360681uid: "fc21281b3e_ge3dunjshizdo"ver: "4.0.166"windowID: "99a6bf0489"proto: Object
